ExponentialRand and Thread creation loop
soatec/tarea1 pull request #1
Opened 2020-02-20 09:56 UTC by daalv

- Add exponential rand();
- Add thread creation loop;
- Add semaphore and counter variables;
- Add thread routines frames (GoingWest and GoingEast);
- Add missing flags to makefile.

2020-02-20 15:03 UTC, bolanojor requested changes

2020-02-20 15:03 UTC, bolanojor commented on Makefile
> +	$(CC) $(OBJECTS) -o $@ $(LDFLAGS) -lm -lpthread
Por favor elimine "-lm -lpthread" de esta línea y en la línea 9 ponga "LDFLAGS := -lm -lpthread". La idea de esta variable es mantener todos los requisitos para el link ahí.

2020-02-20 15:03 UTC, bolanojor commented on src/main.c
> +// Argumentos del thread.
Por favor poner el comentario en inglés. Deberíamos de conservar un estándar programando en inglés o en español, por lo que veo la mayoría del código está en inglés.

2020-02-20 15:03 UTC, bolanojor commented on src/main.c
> +    int totalCars = este+oeste;
Mismo comentario respecto al idioma en las siguientes 3 líneas.

2020-02-20 15:03 UTC, bolanojor commented on src/main.c
> +	return -log(1-uniform) * mean;	//Inversion method
Según lo que encontré en internet, debería de ser -log(1-uniform) / mean?

So, generate a uniform random number, u, in [0,1), then calculate x by:
x = log(1-u)/(-λ),
where λ is the rate parameter of the exponential distribution. Now, x is a random number with an exponential distribution. Note that log above is ln, the natural logarithm.
Source: https://stackoverflow.com/questions/2106503/pseudorandom-number-generator-exponential-distribution

2020-02-20 15:03 UTC, bolanojor commented on src/main.c
> +    	sleep(exprand(1));
El profe sugirió preguntar la media de ambas direcciones por consola (una media diferente por cada dirección).

2020-02-20 15:03 UTC, bolanojor commented on src/main.c
> +    	void *thread_func;
Leyendo de la tarea, entiendo que necesitamos dos procesos para crear hilos, uno que cree los que van hacia el este y otro que cree los que van hacia el oeste. Entiendo que cada proceso es independiente y la media de la función exponencial utilizada debe ser diferente.
También necesitamos que los hilos tengan mínimo ubicación en X dentro de sus propiedades, para delimitar en cuáles ubicaciones de X está el puente que sólo tiene vía hacia una dirección donde los hilos deben esperar.

2020-02-20 15:56 UTC, daalv commented on Makefile
> +	$(CC) $(OBJECTS) -o $@ $(LDFLAGS) -lm -lpthread
oka 👍

2020-02-20 15:56 UTC, daalv commented on src/main.c
> +// Argumentos del thread.
oka 👍

2020-02-20 15:56 UTC, daalv commented on src/main.c
> +    int totalCars = este+oeste;
oka 👍

2020-02-20 15:56 UTC, daalv commented on src/main.c
> +	return -log(1-uniform) * mean;	//Inversion method
hay 2 formas: que reciba de input lambda, o el mean.
- con input lambda es: -log(1-uniform) / lambda
- para input mean, lambda = 1/mean [[1],](https://stackoverflow.com/a/11491526) por eso: -log(1-uniform) * mean

Luego el uniform number lo hago poquito mayor a 0 y poquito menor a 1 porque:
- si es 1 da a infinito
- si es 0 entonces log(1-0)=0 -> 0*mean = 0

2020-02-20 16:49 UTC, bolanojor approved these changes

2020-02-20 16:51 UTC, bolanojor commented on src/main.c
> +	return -log(1-uniform) * mean;	//Inversion method
Entiendo. Gracias por la explicación :)

2020-02-21 01:17 UTC, gariasmontiel commented on src/main.c
> +    	void *thread_func;
creo que esto se puede arreglar usano un semaforo para bloquear los hilos que va a una direccion luego liberarlo para que pase el otro.. no se si a eso se feriere..

2020-02-21 01:20 UTC, pandikai approved these changes

2020-02-21 01:21 UTC, gariasmontiel approved these changes

2020-02-21 01:22 UTC, merged