Alonso
soatec/tarea1 pull request #2
Opened 2020-02-21 08:04 UTC by Aloti

2020-02-21 15:35 UTC, bolanojor requested changes

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
> +#define TRUE 	1
Las definiciones de true y false están disponibles en C si incluye este header: <stdbool.h>

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
> +#define WEST	1
En lugar de estas definiciones será posible utilizar el enum de Daniel? crossingDirection. Talvez se puede renombrar a DIrection y de ahí comparar a ToEast y ToWest para saber la dirección.

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
>  int crosingCounter, waitingToEastCounter, waitingToWestCounter;
Si no vamos a utlizar estas variables, es mejor borrarlas.

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
>      while ((opt = getopt(argc, argv, "e:o:")) != -1) {
Aquí falta agregar dos parámetros para las medias de cada dirección.

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
> +	pthread_t creator[2];
Podemos subir estas definiciones al inicio para que estén continuas por favor?

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
>      int i;
Podemos subir estas definiciones para que estén contínuas por favor.

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
> +
Podemos eliminar esto por favor?

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
> +}
Por orden y para faciliar la revisión sería bueno mover estas funciones a un .c y .h aparte e incluirlas aquí.

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
> +	enterBridge(1, tID);
En lugar de un número por favor usar el enumerado Direction para que quede clara la dirección a cualquier persona.

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
> +void *createWestCars(void *arg){
Esta función es prácticamente igual a createEastCars. No se podrá parametrizar la dirección, la media y la cantidad de carros para usar una sola función?

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
> +		sleep(exprand(1));
La media se debe obtener de consola

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
> +		if(errCheck = pthread_create(&thread[i], NULL, GoingWest, &cData[i])){
Lo carros deberían de tener otra estructura de información diferente a la de los creadores que contenga threadID, xPosition y Direction. O algo así.

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
>  //••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••FUNCTIONS
Deberíamos de tener dos límites en X de inicio y fin de la calle para saber cuándo un hilo terminó de cruzarla y terminar su ejecución.

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
> +	enterBridge(1, tID);
Deberíamos de tener una posición en X para el inicio y fin del puente.

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
> +	sleep(1);
Los carros deberían de tener una posición que vaya aumentando aquí.

2020-02-21 15:35 UTC, bolanojor commented on src/main.c
> +	enterBridge(0, tID);
Los mismos comentarios de arriba aplican para esta dirección. Las funciones son tan parecidas que siento que es posible parametrizarlas.

2020-02-22 05:16 UTC, Aloti commented on src/main.c
>      while ((opt = getopt(argc, argv, "e:o:")) != -1) {
esto le toca a @daalv

2020-02-22 12:50 UTC, bolanojor approved these changes

2020-02-22 12:53 UTC, merged